npx helpers
devforth/adminforth pull request #13
Opened 2024-11-06 13:16 UTC by SerVitasik

2024-11-06 13:36 UTC, ivictbor requested changes

2024-11-06 13:36 UTC, ivictbor commented on adminforth/commands/bundle.js
> +  const instance = await generateModels();
@SerVitasik do we need to generate models before bundle, I think no? Maybe this function should be called `findInstance()`

2024-11-06 13:36 UTC, ivictbor commented on adminforth/commands/utils.js
> +    case "json":
for json we need an `any` type

2024-11-06 13:36 UTC, ivictbor commented on adminforth/package-lock.json
> +<<<<<<< HEAD
@SerVitasik I think this should not be here 

![PedroMonkeyPuppetGIF (2)](https://github.com/user-attachments/assets/218e167e-90d7-4a1d-9a8f-813e79f1be82)

2024-11-06 13:36 UTC, ivictbor commented on dev-demo/tsconfig.json
> +    "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
@SerVitasik do we need this?

2024-11-06 13:36 UTC, ivictbor commented on adminforth/commands/generateModels.js
> +      const match = fileContent.match(adminForthPattern);
* maybe user might have `let` instead of `const`, lets use const|let
* check case when file not found at all and say clearly to user in console.error that you was not able to find `const|let * = new AdminForth(`
* if two regexp instances were found - console.error in which files and return, we don't know what to do
* if export was not provided, say that his match[1]

2024-11-06 13:36 UTC, ivictbor commented on adminforth/commands/generateModels.js
> +  const files = fs.readdirSync(currentDirectory);
@SerVitasik maybe it makes sense to find files recuresively down from currentDirectory

if I do npx adminforth bundle from `/home/a` and have admin constant in `/home/a/b/main.js` it should find it, can you test it also?

2024-11-06 14:22 UTC, SerVitasik commented on adminforth/package-lock.json
> +<<<<<<< HEAD
:\

2024-11-08 08:16 UTC, ivictbor approved these changes

2024-11-08 08:17 UTC, merged